[package]
name = "redshell"
version = "0.0.1"
edition = "2018"

[features]
force_out_test = []
force_out_ansi = []
force_in_blank = []

[dependencies]
paste = "1.0.5"
rand = { version = "0.8.4", features = [ "small_rng" ] }
crossterm = "0.20.0"
tokio = { version = "1.15.0", features = [ "full" ] }
enum_dispatch = "0.3.7"
async-trait = "0.1.52"
