[package]
name = "redshell"
version = "0.0.2"
edition = "2018"
description = "A console-based hacking game. Currently building the engine to support dual TUI/GUI interfaces."
license = "BSD-3-Clause"

[features]
default = ["sys_cli"]
sys_test = []
sys_cli = ["crossterm"]
sys_gui = []
sys_gui_cpu = ["sys_gui"]
sys_gui_opengl = ["sys_gui"]
sys_gui_vulkan = ["sys_gui"]

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
strip = true

[dependencies]
paste = "1.0.5"
crossterm = { version = "0.20.0", optional = true }
tokio = { version = "1.15.0", features = [ "full" ] }
enum_dispatch = "0.3.7"
async-trait = "0.1.52"
