[package]
name = "tuig"
version = "0.0.1"
edition = "2021"

[features]
# See tuig::docs::features for crucial information.
__io = []
io_nop = []
io_cli = []
__io_gui = []
io_gui_softbuffer = []

__run = []
run_orig = []
run_single = []
run_rayon = []

test_extras = []

[dependencies]
tuig-iosys = { path = "../tuig-iosys" }
tuig-pm = { path = "../tuig-pm" }
