name: Build packages
run-name: Building ${{github.ref_name}} deployables
on:
  push:
    tags:
    - 'v**'
    branches-ignore:
    - '**'
jobs:


  plain-bin:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu, windows, macos]
        # TODO: Replace with `plat_` eventually
        sys: [cli, gui_softbuffer]
        include:
        - ext: ''
        - platform: windows
          ext: '.exe'
    name: Build plain-bin-${{ matrix.sys }}-${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}-latest
    steps:
    - uses: actions/cache@v3
      with:
        path: ~/.rustup/
        key: rustup-${{matrix.platform}}-stable
    - uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: cargo-cache
    - uses: actions/cache@v3
      with:
        path: ./target
        key: target-dir-${{matrix.platform}}-stable
    - name: Set up Rust
      run: |
        rustup default stable

    - uses: actions/checkout@v3
    - name: Generate artifact
      run: |
        cargo build --release --features io_${{ matrix.sys }} --bins

    - uses: actions/upload-artifact@v3
      with:
        name: plain-bin-${{ matrix.sys }}-${{ matrix.platform }}
        path: |
          target/release/redshell${{ matrix.ext }}
          target/release/redshell-concept${{ matrix.ext }}
        if-no-files-found: error
