name: Build packages
run-name: Building ${{github.ref_name}} deployables
on:
  push:
    tags:
    - 'v**'
    branches-ignore:
    - '**'
jobs:


  desktop-bin:
    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu]
        plat: [ssh, steam]
        include:
        - ext: ''
        - os: windows
          ext: '.exe'
    name: Build desktop-bin-${{ matrix.plat }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/cache@v3
      with:
        path: ~/.rustup/
        key: rustup-${{matrix.os}}-stable
    - uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: cargo-cache
    - uses: actions/cache@v3
      with:
        path: ./target
        key: target-dir-${{matrix.os}}-stable
    - name: Set up Rust
      run: |
        rustup default stable

    - uses: actions/checkout@v3
    - name: Generate artifact
      run: |
        cargo build --release --features plat_{{ matrix.plat }}

    - uses: actions/upload-artifact@v3
      with:
        name: desktop-bin-${{ matrix.plat }}-${{ matrix.os }}
        path: |
          target/release/redshell${{ matrix.ext }}
        if-no-files-found: error
