name: Build packages
run-name: Building ${{github.ref_name}} deployables
on:
  push:
    tags:
    - v*
    branches-ignore:
    - '**'
jobs:
  x86-bin:
    strategy:
      matrix:
        platform: [ubuntu, windows, macos]
        sys: [cli]
        include:
        - ext: ''
        - platform: windows
          ext: '.exe'
    runs-on: ${{ matrix.platform }}-latest
    name: x86-bin-${{ matrix.sys }}-${{ matrix.platform }}
    steps:
    # load caches if they're available
    - uses: actions/cache@v3
      with:
        path: ~/.rustup/
        key: rustup-${{matrix.platform}}-stable
    - uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: cargo-cache
    - uses: actions/cache@v3
      with:
        path: ./target
        key: target-dir-${{matrix.platform}}-stable

    - uses: actions/checkout@v3
    - run: rustup default stable
    # TODO: Replace with `plat_cli` and `plat_gui` eventually
    - run: cargo build --release --features sys_${{ matrix.sys }}
    - uses: actions/upload-artifact@v3
      with:
        name: x86-bin-${{ matrix.sys }}-${{ matrix.platform }}
        path: |
          target/release/redshell${{ matrix.ext }}
        if-no-files-found: error
