name: Run test battery
run-name: Testing ${{github.ref_name}}
# no permission for the token, this runs on pull requests
permissions: {}
on:
  push:
    tags-ignore: '**'
    branches: '**'
  schedule:
  # run twice a week to keep mostly up-to-date with crate updates, nightly
  - cron: '0 0 * * 0,3'
jobs:


  unit-and-integration:
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, 1.59, nightly]
        platform: [windows, macos, ubuntu]
    name: ${{ matrix.platform }} / Rust ${{ matrix.rust }}
    runs-on: ${{ matrix.platform }}-latest
    steps:
    - uses: actions/cache@v3
      with:
        path: ~/.rustup/
        key: rustup-${{ matrix.platform }}-${{ matrix.rust }}
    - uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: cargo-cache
    - uses: actions/cache@v3
      with:
        path: ./target
        key: target-dir-${{ matrix.platform }}-${{ matrix.rust }}
    - name: Set up Rust
      run: |
        rustup default ${{ matrix.rust }}
        rustup component add rustfmt

    - uses: actions/checkout@v3
    - name: Run tests
      run: |
        cargo fmt --check
        cargo check --all-features
        cargo test --all-features


  mass-events:
    # Only run this once the other, shorter tests are done.
    needs: unit-and-integration
    strategy:
      fail-fast: false
      matrix:
        runner: [orig, single]
    name: ${{ matrix.runner }} runner
    runs-on: linux-latest
    steps:
    - uses: actions/cache@v3
      with:
        path: ~/.rustup/
        key: rustup-linux-stable
    - uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: cargo-cache
    - uses: actions/cache@v3
      with:
        path: ./target
        key: target-dir-linux-stable
    - name: Set up Rust
      run: |
        rustup default stable
        rustup component add rustfmt

    - uses: actions/checkout@v3
    - name: Run tests
      run: |
        cargo run --release --bin mass-events --features sys_nop,run_${{ matrix.runner }}
