name: Tests
run-name: Testing ${{github.ref_name}}
# no permission for the token, this runs on pull requests
permissions: {}
on:
  push:
    tags-ignore: '**'
    branches: '**'
  schedule:
  # run twice a week to keep mostly up-to-date with crate updates, nightly
  - cron: '0 0 * * 0,3'
jobs:


  unit-and-integration:
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, "1.64", nightly]
        platform: [windows, macos, ubuntu]
    name: Rust ${{ matrix.rust }} / ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}-latest
    steps:
    - uses: actions/cache@v3
      with:
        path: ~/.rustup/
        key: rustup-${{ matrix.platform }}-${{ matrix.rust }}
    - uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: cargo-cache
    - uses: actions/cache@v3
      with:
        path: ./target
        key: target-dir-${{ matrix.platform }}-${{ matrix.rust }}
    - name: Set up Rust
      run: |
        rustup default ${{ matrix.rust }}
        rustup component add rustfmt

    - uses: actions/checkout@v3
    - name: Run tests
      run: |
        cargo fmt --check
        cargo check --all-features
        cargo test --all-features


  mass-events:
    strategy:
      fail-fast: false
      matrix:
        run: [orig, single, rayon]
        include:
        - std: ""
        - run: rayon
          std: "std"
        - run: orig
          std: "std"
    name: Runner ${{ matrix.run }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v3
      with:
        path: ~/.rustup/
        key: rustup-ubuntu-stable
    - uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: cargo-cache
    - uses: actions/cache@v3
      with:
        path: ./target
        key: target-dir-ubuntu-stable
    - name: Set up Rust
      run: |
        rustup default stable

    - uses: actions/checkout@v3
    - name: Deploy events
      run: |
        cargo run --release --bin mass-events --features io_nop,run_${{ matrix.run }},${{ matrix.std }}


  exhaustive-features:
    strategy:
      fail-fast: false
      matrix:
        run: [orig, single, rayon]  # TODO: std_multi
        sys: [nop, cli_crossterm, gui_softbuffer]
        include:
        - std: ""
        - run: orig
          std: "std"
        - run: rayon
          std: "std"
        - sys: nop
          std: "std"
        - sys: cli_crossterm
          std: "std"
        - sys: gui_softbuffer
          std: "std"
    name: Check run_${{ matrix.run }} and io_${{ matrix.sys }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v3
      with:
        path: ~/.rustup/
        key: rustup-ubuntu-stable
    - uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: cargo-cache
    - uses: actions/cache@v3
      with:
        path: ./target
        key: target-dir-ubuntu-stable
    - name: Set up Rust
      run: |
        rustup default stable

    - uses: actions/checkout@v3
    - name: Check feature compatibility
      run: |
        cargo check --features io_${{ matrix.sys }},run_${{ matrix.run }},${{ matrix.std }} --all-targets
