name: Run tests
run-name: Testing ${{github.ref}}
on:
  push:
    tags-ignore: *
jobs:
  fmt-and-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cargo fmt --check
  test:
    strategy:
      matrix:
        rust: [stable, nightly]
        platform: [windows, macos, ubuntu]
        # TODO: features: [plat_x86, plat_steam, etc]
        include:
        - failable: true
        - rust: stable
          failable: false
    runs-on: ${{ matrix.platform }}-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup update
    - run: rustup default ${{ matrix.rust }}
    - run: cargo check
    - run: cargo test
