name: Run tests
run-name: Testing ${{github.ref_name}} (${{github.sha}})
# no permission for the token, this runs on pull requests
permissions: {}
on:
  push:
    tags-ignore: '**'
    branches: '**'
  schedule:
  # run twice a week to keep mostly up-to-date with crate updates, nightly
  - cron: '0 0 * * 0,3'
jobs:

  test:
    strategy:
      matrix:
        rust: [stable, nightly, 1.59]
        platform: [windows, macos, ubuntu]
        include:
        - fail_ok: false
        - rust: nightly
          fail_ok: true
    name: On ${{ matrix.platform }} w/ Rust ${{ matrix.rust }}
    needs: check
    runs-on: ${{ matrix.platform }}-latest
    steps:
    - uses: actions/cache@v3
      with:
        path: ~/.rustup/
        key: rustup-${{ matrix.platform }}-${{ matrix.rust }}
    - uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: cargo-cache
    - uses: actions/cache@v3
      with:
        path: ./target
        key: target-dir-${{ matrix.platform }}-${{ matrix.rust }}

    - uses: actions/checkout@v3
    - run: rustup default ${{ matrix.rust }}
    - run: rustup component add rustfmt
    - run: cargo fmt --check
      continue-on-error: ${{ matrix.fail_ok }}
    - run: cargo check --all-features
      continue-on-error: ${{ matrix.fail_ok }}
    - run: cargo test --all-features
      continue-on-error: ${{ matrix.fail_ok }}
