name: Pre-merge tests
run-name: Testing ${{github.ref_name}}
# no permission for the token, this runs on pull requests
permissions: {}
on:
  push:
    tags-ignore: '**'
    branches: '**'
  schedule:
  # run twice a week to keep mostly up-to-date with crate updates, nightly
  - cron: '0 0 * * 0,3'
jobs:


  unit-and-integration:
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, "1.64", nightly]
        os: [windows, ubuntu]
        plat: [ssh, steam]
    name: Rust ${{ matrix.rust }} on ${{ matrix.os }} for platform ${{ matrix.plat }}
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/cache@v3
      with:
        path: ~/.rustup/
        key: rustup-${{ matrix.os }}-${{ matrix.rust }}
    - uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: cargo-cache
    - uses: actions/cache@v3
      with:
        path: ./target
        key: target-dir-${{ matrix.os }}-${{ matrix.rust }}
    - name: Set up Rust
      run: |
        rustup default ${{ matrix.rust }}
        rustup component add rustfmt

    - uses: actions/checkout@v3
    - name: Run tests
      env:
        features: plat_${{ matrix.plat }}
      run: |
        cargo fmt --check
        cargo check --features "${{ env.features }}" --all-targets
        cargo test --features "${{ env.features }}" --all-targets
