name: Run tests
run-name: Testing ${{github.ref_name}} (${{github.sha}})
# no permission for the token, this runs on pull requests
permissions: {}
on:
  push:
    tags-ignore: '**'
    branches: '**'
  schedule:
  # run twice a week to keep mostly up-to-date with nightly changes and new versions
  - cron: '0 0 * * 0,3'
jobs:
  fmt-and-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cargo fmt --check
    - run: cargo check --all-features
    - uses: actions/cache@v3
      with:
        path: |
          ~/.rustup/
          ~/.cargo/
        key: rust-stuff
    - uses: actions/cache@v3
      with:
        path: |
          ./target
        key: target-dir
  test:
    needs: fmt-and-check
    strategy:
      matrix:
        rust: [stable, nightly, 1.59]
        platform: [windows, macos, ubuntu]
        # TODO: features: [plat_x86, plat_steam, etc]
        include:
        - failable: true
        - rust: stable
          failable: false
    name: ${{ matrix.platform }} rustc-${{ matrix.rust }}
    runs-on: ${{ matrix.platform }}-latest
    steps:
    - if: matrix.platform == "ubuntu"
      uses: actions/cache@v3
      with:
        path: |
          ~/.rustup/
          ~/.cargo/
        key: rust-stuff
    - if: matrix.platform == "ubuntu"
      uses: actions/cache@v3
      with:
        path: |
          ./target
        key: target-dir
    - uses: actions/checkout@v3
    - run: rustup update
    - run: rustup default ${{ matrix.rust }}
    - run: cargo test --all-features
      continue-on-error: ${{ matrix.failable }}
